# Generated by Django 4.1.1 on 2022-09-18 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='userinfo.basemodel')),
                ('designation', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=100)),
                ('about_me', models.CharField(max_length=250)),
                ('banner_image', models.URLField(max_length=350)),
                ('footer_image', models.URLField(max_length=350)),
                ('facebook_id', models.URLField()),
                ('linked_id', models.URLField()),
                ('github_id', models.URLField()),
                ('cv_link', models.URLField(max_length=350)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('userinfo.basemodel',),
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='userinfo.basemodel')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=350)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_service', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('userinfo.basemodel',),
        ),
        migrations.CreateModel(
            name='ProfessionalSkills',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='userinfo.basemodel')),
                ('skill_logo', models.URLField(max_length=250)),
                ('skill_name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_skill', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('userinfo.basemodel',),
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='userinfo.basemodel')),
                ('project_name', models.CharField(max_length=150)),
                ('project_img', models.URLField(max_length=350)),
                ('preview_link', models.URLField(max_length=350)),
                ('github_link', models.URLField(max_length=350)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_portfolio', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('userinfo.basemodel',),
        ),
        migrations.CreateModel(
            name='Experince',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='userinfo.basemodel')),
                ('company_name', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=150)),
                ('join_year', models.IntegerField()),
                ('resign_year', models.IntegerField()),
                ('responsibility', models.TextField(max_length=350)),
                ('company_logo', models.URLField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_experience', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('userinfo.basemodel',),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='userinfo.basemodel')),
                ('degree_name', models.CharField(max_length=150)),
                ('subject', models.CharField(max_length=150)),
                ('institute', models.CharField(max_length=250)),
                ('start_year', models.IntegerField()),
                ('passing_year', models.IntegerField()),
                ('short_brief', models.TextField(max_length=350)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_education', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('userinfo.basemodel',),
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='userinfo.basemodel')),
                ('name', models.CharField(max_length=150)),
                ('phone_no', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('subject', models.CharField(max_length=250)),
                ('message', models.TextField(max_length=350)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_request', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('userinfo.basemodel',),
        ),
        migrations.CreateModel(
            name='ClientFeedback',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='userinfo.basemodel')),
                ('client_name', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=150)),
                ('company_name', models.CharField(max_length=150)),
                ('client_photo', models.URLField(max_length=350)),
                ('job_title', models.CharField(max_length=250)),
                ('market_place', models.CharField(max_length=150)),
                ('contract_start', models.DateField()),
                ('contract_end', models.DateField()),
                ('rating', models.FloatField()),
                ('feedback', models.TextField(max_length=350)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('userinfo.basemodel',),
        ),
    ]
